### ISSUE TITLE
A question about baseline MT-LSTM-CRF

### ISSUE THREAD

**Issue by wjczf123** [LiyingCheng95/ArgumentPairExtraction#1]
The MT-LSTM-CRF uses S-LSTM to replace T-LSTM or just removes T-LSTM?

**Comment by LiyingCheng95** [comment]
Remove T-LSTM. For MT-LSTM-CRF, we use pre-trained BERT CLS token as sentence embedding.

**Comment by wjczf123** [comment]
OK. Thank you a lot.

**Comment by wjczf123** [comment]
using GPU... 0
Reading file: data/rr-passage/train.txt
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/deepo_data/APE/trainer.py in <module>
    314 
    315 if __name__ == "__main__":
--> 316     main()

/deepo_data/APE/trainer.py in main()
    283     set_seed(opt, conf.seed)
    284 
--> 285     trains = reader.read_txt(conf.train_file, conf.train_num)
    286     devs = reader.read_txt(conf.dev_file, conf.dev_num)
    287     tests = reader.read_txt(conf.test_file, conf.test_num)

/deepo_data/APE/config/reader.py in read_txt(self, file, number)
     27 
     28         # f_vec = open(file[:8]+'vec_test.pkl', 'rb')
---> 29         f_vec = open(file[:8] + 'vec_' + file[8:-3] + 'pkl', 'rb')
     30         all_vecs = pickle.load(f_vec)
     31         f_vec.close

FileNotFoundError: [Errno 2] No such file or directory: 'data/rr-vec_passage/train.pkl'

**Comment by wjczf123** [comment]
There was a problem with data processing while I was running. 
Do I need to process the data first? 
Can you tell me how to process the data?
