### ISSUE TITLE
RR-submission-v2标签不一致问题

### ISSUE THREAD

**Issue by guanminzhao** [LiyingCheng95/ArgumentPairExtraction#10]
图片里的数字为什么“1.”标签是“I-Reply	I-1”而“2.”却是“O	O”

![屏幕截图 2022-10-14 205822](https://user-images.githubusercontent.com/89442650/195853689-e5324c0b-9a45-4b8b-ba48-4159e89bc578.png)

**Comment by LiyingCheng95** [comment]
这里的case是因为前一句是“Author Response: To reinforce this aspect, since initial submission we have found the following ways to surpass the performance we initially reported:”，而这句话不能作为独立的一个rebuttal argument，所以标注的时候对这种情况会跟下文合并成一个argument，就把第一个序号算进去了。之后如果想到更好的切分方法，也可以进一步改进这个数据集。

**Comment by guanminzhao** [comment]
好的，谢谢解答
