### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wjczf123** [LiyingCheng95/ArgumentPairExtraction#3]
There are still some problems. 
in reader.py :

                    type_id = 1
                    if line_idx<len(f)-2:
                        #print(f[line_idx+2].rstrip().split('\t'))
                        if label[0] != 'O' or (label[0]=='O' and ( (new_index>0 and f[line_idx-1].rstrip().split('\t')[1][0] != 'O') or
                                                               (new_index>1 and f[line_idx-2].rstrip().split('\t')[1][0] != 'O') or
                                                               (f[line_idx+1]!='' and f[line_idx+1].rstrip().split('\t')[1][0] != 'O') or
                                                               (f[line_idx+1]!='' and f[line_idx+2]!='' and f[line_idx+2].rstrip().split('\t')[1][0] != 'O' ))):
                            reply_idx.append(sent_idx)
                    elif line_idx==len(f)-2:
                        if f[line_idx + 1].rstrip() != '':
                            if label[0] != 'O' or (label[0] == 'O' and (
                                    (new_index > 0 and f[line_idx - 1].rstrip().split('\t')[1][0] != 'O') or
                                    (new_index > 1 and f[line_idx - 2].rstrip().split('\t')[1][0] != 'O') or
                                    (f[line_idx + 1] != '' and f[line_idx + 1].rstrip().split('\t')[1][0] != 'O'))):
                                reply_idx.append(sent_idx)
                        else:
                            if label[0] != 'O' or (label[0] == 'O' and (
                                    (new_index > 0 and f[line_idx - 1].rstrip().split('\t')[1][0] != 'O') or
                                    (new_index > 1 and f[line_idx - 2].rstrip().split('\t')[1][0] != 'O'))):
                                reply_idx.append(sent_idx)

                    elif line_idx==len(f)-1:
                        if label[0] != 'O' or (label[0]=='O' and ( (new_index>0 and f[line_idx-1].rstrip().split('\t')[1][0] != 'O') or
                                                               (new_index>1 and f[line_idx-2].rstrip().split('\t')[1][0] != 'O'))):
                            reply_idx.append(sent_idx)

I found that len(f)=160090. line_idx<len(f)-2 often ture. However f[line_idx+2].rstrip().split('\t')[1][0] != 'O' and f[line_idx+2].rstrip().split('\t')[1][0] != 'O' happens index error (f[line_idx+2] or f[line_idx+1] is '').

**Comment by LiyingCheng95** [comment]
Kindly try again. I have updated the reader.py and utils.py.

**Comment by wjczf123** [comment]
1. 
I can run the code by changing self.lstm = nn.LSTM(self.input_size, config.hidden_dim // 2, num_layers=self.num_layers, batch_first=True, bidirectional=True).to(self.device) to self.lstm = nn.LSTM(788, config.hidden_dim // 2, num_layers=self.num_layers, batch_first=True, bidirectional=True).to(self.device) in modelrr/bilstm_encoder.

2. But my model is doesn't work. Can you make sure the code is right?

3. Is there any difference between model and modelrr?

**Comment by LiyingCheng95** [comment]
Can you give me your email address? I will send u the most updated code. I need some time to double check this version.

**Comment by LiyingCheng95** [comment]
Kindly ignore the model folder. Just use the modelrr folder.

**Comment by wjczf123** [comment]
1044795134@qq.com. Thank you a lot.
