### ISSUE TITLE
ReviewRebuttalnew2.txt

### ISSUE THREAD

**Issue by benjpau** [LiyingCheng95/ArgumentPairExtraction#5]
Sorry to bother you. I didn't find the ReviewRebuttalnew2.txt file in this repo. Would you please tell me where I can download it? Thanks a lot!

**Comment by LiyingCheng95** [comment]
I have uploaded the file in the data folder. Kindly let me know if there's anything else.

**Comment by benjpau** [comment]
Thanks for your reply.
I still have some questions. After using _data_processing/dataProcessing.py_ to process the _ReviewRebuttalnew2.txt_ file, I input the resulting _vec_train.pkl_, _vec_dev.pkl_ and _vec_test.pkl_ into trainer.py with all default hyperparameters. Then, I can get the results of MT-H-LSTM-CRF (Ours) in Table 3 of your paper. Is that right?

**Comment by LiyingCheng95** [comment]
Yes, correct.
