### ISSUE TITLE
Question about the annotated data.

### ISSUE THREAD

**Issue by benjpau** [LiyingCheng95/ArgumentPairExtraction#6]
Sorry to bother you.
Could you please explain the meaning of the tags in the annotation data file ReviewRebuttalnew2.txt? Especially the labels like 'B-1', 'B-2', 'I-2'.

**Comment by LiyingCheng95** [comment]
We use BIO labeling scheme for sequence labeling. B means the first sentence of the argument, I means the rest sentences of the argument. O means the sentence is not argument. For the index part, it shows the pairing information between review arguments and reply arguments. A review and reply argument pair share the same index. For example, a review argument [B-1, I-1] and a reply argument [B-1, I-1, I-1] are an argument pair. A review argument [B-1, I-1] and a reply argument [B-2, I-2, I-2] are not an argument pair.

**Comment by benjpau** [comment]
Thanks!
