### ISSUE TITLE
Could you please provide the dataset with different difficulty levels？

### ISSUE THREAD

**Issue by benjpau** [LiyingCheng95/ArgumentPairExtraction#7]
In Section 6.3.1 of your paper, the author analyzed **comparison among different difficulty levels**, which I think is very important. So, could you please provide the dataset with different difficulty levels？

**Comment by LiyingCheng95** [comment]
I have added the files in data/RR-submission.
test_level1.txt is the test file with difficulty level at the last column.
all_data_with_level is the file containing all data with difficulty levels. You have to do the paperid matching (the last column in this file) and some text matching if you would like to use the difficulty level for train/dev data.
