### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Fino2020** [LiyingCheng95/ArgumentPairExtraction#9]
![image](https://user-images.githubusercontent.com/66312471/191268738-06aaeead-1135-4073-84f2-260332a6115a.png)
如图，`torch==1.10.0+cu113 allennlp==2.10.0`,请问为啥会出现这个问题呢……

**Comment by LiyingCheng95** [comment]
应该是你的数据问题。这个的输入的pretrained BERT embeddings。
请问你在使用这套框架实现什么任务呢？
如果是APE的任务，你可以使用https://github.com/TianyuTerry/MLMC 这套框架，比较容易跑，效果也会更好。
如果是其他任务，可以参考https://github.com/allanj/pytorch_neural_crf 这套改良版的lstm-crf框架。
